### ISSUE TITLE
Tag new version to allow Symfony 3

### ISSUE THREAD

**Issue by TomasVotruba** [KnpLabs/KnpGaufretteBundle#129]
Symfony 3 is supported on master, yet not tagged so unable to be used by other packages.

Is there something missing to allow new tag?

**Comment by JHGitty** [comment]
+1

**Comment by kilhage** [comment]
:+1:

**Comment by mmoreram** [comment]
:+1: please :)

**Comment by sc0rp10** [comment]
+1

**Comment by Huskynarr** [comment]
+1

**Comment by Icewild** [comment]
+1

**Comment by index0h** [comment]
+1

**Comment by mmoreram** [comment]
If this Saturday there is no tag, I will fork this repository and I will add a new tag.

**Comment by sc0rp10** [comment]
@mmoreram nice idea

**Comment by mmoreram** [comment]
@sc0rp10 I would love not to do this, but is the only way Elcodi can be used with Symfony3 :/

**Comment by TomasVotruba** [comment]
@mmoreram Thanks for making these steps!

**Comment by akovalyov** [comment]
Hi all. 
First of all, I am really sorry for inactivity. Currently we have a lack of active maintainers for it. 
I have just jumped into the project to make my best to merge/tag everything which is needed for the community. 
I have just tagged [0.3.0](https://github.com/KnpLabs/KnpGaufretteBundle/releases/tag/0.3.0) with Symfony3 support just for you.
To be honest, I am quite a newbie as a maintainer and I am new for this project. So, I apologize for the mess for next several weeks in advance. 
Also, only you know your needs better. So, I kindly ask you to create/comment issues, comment PRs so that we can prioritize things and build a good plan. Please, mention me and/or @NiR- and we will get to you ASAP.
I also have created a room in [Gitter](https://gitter.im/KnpLabs/Gaufrette) and I will make my best to be there as much as possible, so just enter/start the discussion. 

I am closing this particular issue since it is resolved.
Thank you.

**Comment by mmoreram** [comment]
Hi there @akovalyov 

First of all, I need to say that I'm seriously impressed. This may be one of the most honest comments in Github I've ever seen. No many people here starts saying "sorry" as a maintainer, and even less in that particular and sincerely way. So... really thank you.

Said that, thanks for that tag. Will really help so many people a lot :)
All maintainers have been newbie at the beginning, so don't apologize for that. What matters here is, always, absolutely always, predisposition, respect and good volunteer. Everything else are just circumstances.

I could have posted this comment in Gitter, but it is my particular way to tell everyone... *Hey guys... take some example...*

About the repository, just count on me with whatever you need. I have some experience in releases and things like these, so just ask me whatever you need. Advises, help for reviewing and merging/tagging.

Be brave, for sure you'll be an amazing maintainer :)

Cheers!

**Comment by akovalyov** [comment]
@mmoreram first of all, thank you for the kind words! That's really inspiring and I am really looking forward to make the lib and bundle better.

As for merging/tagging, I think, even a monkey can handle pressing the green buttons on GitHub . Moreover, I am pretty sure that monkey aware of Gaufrette is more needed atm rather then senior gaufrette dev :tm:. So, don't worry about that.

I really appreciate your help, especially for reviewing things. I am pretty sure that we will need a lot of manual review of devs aware of particular protocol/provider until we find the best way to handle the integration tests.

And well, see you soon!

**Comment by TomasVotruba** [comment]
@akovalyov Thank you a lot!

**Comment by JHGitty** [comment]
@akovalyov Thanks! There are not much maintainer who are so honest to say that. A lot of guys are new as Github maintainer but do not say this like you did. I am sure you can do it! :+1:
