### ISSUE TITLE
Amazon S3 signature version

### ISSUE THREAD

**Issue by obivan86** [KnpLabs/KnpGaufretteBundle#131]
When I try to upload file to amazon s3 I've got message "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256". How to change authorisation mechanism?

**Comment by akovalyov** [comment]
hi @obivan86.
After some digging into google (I haven't had such an issue before), I can provide at least a some sort of answer. According to https://github.com/aws/aws-sdk-php/issues/582#issuecomment-103652294, you need to specify the region explicitly so that S3 SDK can select the correct authorization mechanism. In case if you are using the the bundle, you need to explicitly set the region in https://github.com/KnpLabs/KnpGaufretteBundle#parameters-11 section, `region` key value.

Hope, it helps.
Feel free to reopen the issue, if it doesn't help.
