### ISSUE TITLE
Add listDirectory to FileSystem

### ISSUE THREAD

**Issue by henrypenny** [KnpLabs/KnpGaufretteBundle#187]
Currently to get a directory listing via the FTP adapter I need to do this:

`$filesystem->getAdapter()->listDirectory()`

If I use `$filesystem->listKeys()` I get nearly 100K results.

Surely getting a list of files in the current directory only is a very common use case.

**Comment by nicolasmure** [comment]
Hello @henrypenny ,

Please notice that this issue is about [Gaufrette](https://github.com/KnpLabs/Gaufrette) itself, not the bundle ;)

However, this `listDirectory` method is only available for ftp (and sftp) adapters, so that's why it does not exist on the `Filesystem` itself because it will be irrelevant for other adapters.

IIRC, when used with the ftp adapter, the `listKeys` function  should return infos about both directories and files. But with other adapters, you don'tg always have a notion of directory (I specially think to the cloud ones where all the files are storage objects).

So yes, I suggest that you keep using `$filesystem->getAdapter()->listDirectory()`.

Have a nice day.

**Comment by henrypenny** [comment]
Sorry. I should know the difference between gaufrette and the accompanying bundle. Thanks for the advice.
